### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by Jamster3000** [emilyxietty/ghiblify2-newtab-chrome#3]
I've been wanting verified support for Firefox add-ons for a long time. After testing this functionality on Firefox Nightly, it appears to work exactly the same as in chrome.

Please confirm and verify support for Firefox add-ons, ensuring consistent functionality across all versions of Firefox.

**Comment by emilyxietty** [comment]
The manifest file is slightly different between mozilla and chrome. I've added a new folder (/mozilla) that contains the appropriate manifest. Otherwise, functionality should all be supported in Firefox add-ons.
